contact_links:
  - name: Help & Support
    url: https://github.com/claviska/doxicity/discussions/categories/help
    about: Please don't create issues for personal help requests. Instead, ask your question on the discussion forum.
